"""empty message

Revision ID: d5d46d59d34a
Revises: 4a8348b46009
Create Date: 2021-01-26 19:43:53.139443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d46d59d34a'
down_revision = '4a8348b46009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VenueGenre')
    op.drop_table('ArtistGenre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArtistGenre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ArtistGenre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Artist.id'], name='ArtistGenre_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ArtistGenre_pkey')
    )
    op.create_table('VenueGenre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"VenueGenre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='VenueGenre_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='VenueGenre_pkey')
    )
    # ### end Alembic commands ###
